---
# task file for keepalived_config

- name: Create keepalived watcher script /etc/keepalived/node.sh
  template:
    src: 'node.sh.j2'
    dest: /etc/keepalived/node.sh
    mode: 0755
  notify: restart keepalived

- name: Create keepalived config /etc/keepalived/keepalived.conf
  template:
    src: 'keepalived.conf.j2'
    dest: /etc/keepalived/keepalived.conf
    mode: 0644
  notify: restart keepalived

