---
# task file for keepalived_packages
- name: Install keepalived packages
  apk:
    name: [
    'keepalived',
    'keepalived-sample-config',
    'keepalived-common',
    'keepalived-doc',
    'sipsak',
    ]
    state: present 
  when: ansible_distribution == 'Alpine'
