all:
  hosts:
    k1.0x300.de:
    k2.0x300.de:
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  children:
    kamailio:
      hosts:
        k1.0x300.de:
        k2.0x300.de:
    keepalived:
      hosts:
        k1.0x300.de:
        k2.0x300.de:

