all:
  hosts:
    k1.0x300.de:
    k2.0x300.de:
    strg.0x300.de:
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
    kamailio_sipdomain: "srv08.0x300.de"
    keepalived_interface: "eth0"
    keepalived_virtual_ipaddress: "192.168.122.100"
  children:
    kamailio:
      hosts:
        k1.0x300.de:
        k2.0x300.de:
    keepalived:
      hosts:
        k1.0x300.de:
        k2.0x300.de:

