---

- name: Create kamailio init.d /etc/init.d/kamailio
  template:
    src: 'etc/init.d/kamailio'
    dest: /etc/init.d/kamailio
    owner: root
    group: root
    mode: 0755
  notify: restart kamailio

- name: Create kamailio config /etc/kamailio/kamailio.cfg
  template:
    src: 'etc/kamailio/kamailio.cfg.j2'
    dest: /etc/kamailio/kamailio.cfg
    mode: 0644
  notify: restart kamailio

- name: Create kamailio kamctl config /etc/kamailio/kamctlrc
  template:
    src: 'etc/kamailio/kamctlrc.j2'
    dest: /etc/kamailio/kamctlrc
    mode: 0644

