---

- name: Create kamailio config /etc/kamailio/kamailio.cfg
  template:
    src: 'etc/kamailio/kamailio.cfg.j2'
    dest: /etc/kamailio/kamailio.cfg
    mode: 0644
  notify: restart kamailio

- name: Create kamailio kamctl config /etc/kamailio/kamctlrc
  template:
    src: 'etc/kamailio/kamctlrc.j2'
    dest: /etc/kamailio/kamctlrc
    mode: 0644

